simulation_parameters:
    'name': 'name'
    'scheduledEndTime': 100
    'numberOfInsurers': 10
    'numberOfRiskholders': 1000
    'start_cash_insurer': 1000.0
    'start_cash_customer': 10000.0
    'defaultContractRuntime': 10
    'defaultContractExcess': 100
    'numberOfRiskCategories': 5
    'shareOfCorrelatedRisk': 0.5
    'numberOfRiskCategoryDimensions': 1
    'series': 'testing'#,
